baseURL = "/"
languageCode = "en-us"
title = "CodeYourFuture Curriculum"
languageLang = "en"
sectionPagesMenu = "main"
enableEmoji = true

[menus]
    [[menus.secondary]]
        name = "Guides ğŸ‘ˆğŸ¾"
        weight = 1
        url = "/guides"
     [[menus.secondary]]
        name = "Join Us ğŸ‘‹ğŸ¿"
        weight = 2
        url = "https://codeyourfuture.io/volunteers/"
    [[menus.secondary]]
        name = "Support ğŸ«¶ğŸ¼"
        weight = 3
        url = "https://codeyourfuture.io/donate/"

[params]
description = "A free and open source software development programme."
org = "https://github.com/CodeYourFuture"
repo = "https://github.com/CodeYourFuture/curriculum/"
tree = "https://github.com/CodeYourFuture/curriculum/tree/main/"
edit = "https://github.com/CodeYourFuture/curriculum/edit/main/"
root = "curriculum"
orgapi = "https://api.github.com/repos/CodeYourFuture/"
# We use a proxy which concatenates paginated responses, otherwise we miss results.
# Daniel is currently hosting this code https://github.com/illicitonion/github-issue-proxy but we should work out a long-term maintainable solution to this problem.
issuesorgapi = "https://github-issue-proxy.illicitonion.com/repos/CodeYourFuture/"

[markup]
[markup.tableOfContents]
endLevel = 2
ordered = true
startLevel = 2
[markup.highlight]
lineNos = false
codeFences = true
guessSyntax = true
[markup.goldmark.renderer]
# Enable HTML codeblocks, e.g. for <details> blocks
unsafe = true
hardWraps = true
disableKinds = ["taxonomy", "term"]
footnote= true

[caches.getjson]
# Disable caching of fetches - we want every build to get up to date content for issues, so that if people make clarifications or fixes to issues, we pick them up.
maxAge = 0

[security.funcs]
# Allow accessing a GitHub bearer token to avoid rate limits when doing HTTP fetches to the GitHub API.
# This can be generated at https://github.com/settings/tokens?type=beta and needs read-only access to all public CYF GitHub repos.
getenv = ["^CYF_CURRICULUM_GITHUB_BEARER_TOKEN$"]
