title = "SDC"
baseURL = "https://sdc.codeyourfuture.io/"

[module]
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/org-cyf-theme"
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/org-cyf-guides" 
    [[module.imports.mounts]]
      source = "content"
      target = "content/guides"
  [[module.imports]]
    path = "github.com/CodeYourFuture/CYF-PD" 
    [[module.imports.mounts]]
      source = "content/blocks"
      target = "content/pd/blocks"
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/org-cyf-how-this-works"
    [[module.imports.mounts]]
      source = "content"
      target = "content/how-this-works"


[params]
googleFonts="https://fonts.googleapis.com/css2?family=Raleway:wght@400;700&display=swap"

[markup]
# I've configured markdown so you don't have to
  [markup.tableOfContents]
    endLevel = 2
    ordered = true
    startLevel = 2
    [markup.goldmark.renderer]
# Enable HTML codeblocks, e.g. for <details> blocks
      unsafe = true
#this makes the section nav go the right way
# because of this 'unexpected behaviour' https://gohugo.io/methods/page/nextinsection/
[page]
  nextPrevInSectionSortOrder = 'asc'
  nextPrevSortOrder = 'asc'
