# This config is optimised for speed of local interaction of general Hugo set-up without worrying about issue freshness or completeness.
# To build with this config, run `hugo server --environment development`.
# Uncomment the following line to run when rate limited or unable to fetch
#ignoreLogs = ['error-remote-getjson']
[params]
# Uncomment the following line to grab just one page of issues/prs for speedier builds
# This means the backlog might not be complete
#orgapi = "https://api.github.com/repos/CodeYourFuture/"
[caches.getjson]
# Cache JSON responses because making fetches is slow when iterating.
# This means updates to issues (or newly created ones) won't be picked up when rebuilding.
maxAge = "6h"
[caches.getresource]
maxAge = "6h"

