title = "Intro to Digital"
description="Meet the world of tech in 30 days"

[module]
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/common-theme" 
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/common-content" 
    [[module.imports.mounts]]
      source = "en"
      target = "content"
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/org-cyf-theme"
      
[menus]
    [[menus.secondary]]
        name = "ITD ğŸ‘ˆğŸ¾"
        weight = 1
        url = "https://codeyourfuture.io/itc/"
     [[menus.secondary]]
        name = "Join Us ğŸ‘‹ğŸ¿"
        weight = 2
        url = "https://codeyourfuture.io/volunteers/"
    [[menus.secondary]]
        name = "Support ğŸ«¶ğŸ¼"
        weight = 3
        url = "https://codeyourfuture.io/donate/"

theme = "common-theme"