title = "Intro to Digital"
description="Meet the world of tech in 30 days"

[module]
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/org-cyf-theme"
      
[menus]
    [[menus.secondary]]
        name = "ITD ğŸ‘ˆğŸ¾"
        weight = 1
        url = "https://codeyourfuture.io/itc/"
     [[menus.secondary]]
        name = "Join Us ğŸ‘‹ğŸ¿"
        weight = 2
        url = "https://codeyourfuture.io/volunteers/"
    [[menus.secondary]]
        name = "Support ğŸ«¶ğŸ¼"
        weight = 3
        url = "https://codeyourfuture.io/donate/"

[markup]
# I've configured markdown so you don't have to
  [markup.tableOfContents]
    endLevel = 2
    ordered = true
    startLevel = 2
    [markup.goldmark.renderer]
# Enable HTML codeblocks, e.g. for <details> blocks
      unsafe = true
