title = "The longed for documentation"

[module]
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/common-theme" 
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/common-content" 
    [[module.imports.mounts]]
      source = "en"
      target = "content/common"

[menus]
    [[menus.secondary]]
        name = "Guides ğŸ‘ˆğŸ¾"
        weight = 1
        url = "/guides"
     [[menus.secondary]]
        name = "Join Us ğŸ‘‹ğŸ¿"
        weight = 2
        url = "https://codeyourfuture.io/volunteer/"
    [[menus.secondary]]
        name = "Support ğŸ«¶ğŸ¼"
        weight = 3
        url = "https://codeyourfuture.io/donate"    

[params]
googleFonts="https://fonts.googleapis.com/css2?family=Oswald:wght@400;700&display=swap"
description = "A free and open source software development programme."
main_website = "https://curriculum.codeyourfuture.io/"
main_org_name = "Code Your Future"
our_name="The Docs"
org = "https://github.com/CodeYourFuture"
repo = "https://github.com/CodeYourFuture/curriculum/"
root = "curriculum"
orgapi = "https://api.github.com/repos/CodeYourFuture"
[caches.getresource]
maxAge="6h"

[security.funcs]
# Allow accessing a GitHub bearer token to avoid rate limits when doing HTTP fetches to the GitHub API.
# This can be generated at https://github.com/settings/tokens?type=beta and needs read-only access to all public CYF GitHub repos.
getenv = ["^HUGO_CURRICULUM_GITHUB_BEARER_TOKEN$"]

[markup]
[markup.tableOfContents]
endLevel = 2
ordered = true
startLevel = 2
[markup.highlight]
lineNos = false
codeFences = true
guessSyntax = true
[markup.goldmark.renderer]
# Enable HTML codeblocks, e.g. for <details> blocks
unsafe = true
hardWraps = true
disableKinds = ["taxonomy", "term"]
footnote= true

theme = "common-theme"
