title = 'Platform Docs'

[menus]
    [[menus.secondary]]
        name = "Menu 1 ğŸ‘ˆğŸ¾"
        weight = 1
        url = ""
     [[menus.secondary]]
        name = "Menu 2 ğŸ‘‹ğŸ¿"
        weight = 2
        url = ""
    [[menus.secondary]]
        name = "Menu 3 ğŸ«¶ğŸ¼"
        weight = 3
        url = ""


# [module]
#   [[module.imports]]
#     path = "github.com/CodeYourFuture/curriculum/common-theme" 
#   [[module.imports]]
#     path = "github.com/CodeYourFuture/curriculum/common-content" 
#     [[module.imports.mounts]]
#       source = "en"
#       target = "content"

[params]
googleFonts="https://fonts.googleapis.com/css2?family=Kalnia:wght@400;500&family=Quicksand:wght@400;600&display=swap"
description = "A free and open source software development programme."
main_website = "https://curriculum.codeyourfuture.io/"
main_org_name = "Code Your Future"
org = "https://github.com/CodeYourFuture"
repo = "https://github.com/CodeYourFuture/curriculum/"
root = "curriculum"
[security.funcs]
# Allow accessing a GitHub bearer token to avoid rate limits when doing HTTP fetches to the GitHub API.
# This can be generated at https://github.com/settings/tokens?type=beta and needs read-only access to all public CYF GitHub repos.
getenv = ["^HUGO_CURRICULUM_GITHUB_BEARER_TOKEN$"]

[markup]
[markup.tableOfContents]
endLevel = 2
ordered = true
startLevel = 2
[markup.highlight]
lineNos = false
codeFences = true
guessSyntax = true
[markup.goldmark.renderer]
# Enable HTML codeblocks, e.g. for <details> blocks
unsafe = true
hardWraps = true
footnote= true

theme = "common-theme"