title = "The longed for documentation"

[module]
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/common-theme" 
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/common-content" 
    [[module.imports.mounts]]
      source = "en"
      target = "content/common-content"
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/org-cyf-guides" 
    [[module.imports.mounts]]
      source = "content"
      target = "content/more-sources/mounted/guides"
  [[module.imports]]
    path = "github.com/CodeYourFuture/CYF-PD" 
    [[module.imports.mounts]]
      source = "content/"
      target = "content/more-sources/mounted/pd"
  [[module.imports]]
    path = "github.com/CodeYourFuture/CYF-Workshops/micro-front-end" 
    [[module.imports.mounts]]
      source = "content/"
      target = "content/more-sources/mounted/workshops"
  [[module.imports]]
    path = "github.com/CodeYourFuture/CYF-Projects/micro-front-end" 
    [[module.imports.mounts]]
      source = "content/"
      target = "content/more-sources/mounted/projects"

[menus]
    [[menus.secondary]]
        name = "Guides üëàüèæ"
        weight = 1
        url = "/guides"
     [[menus.secondary]]
        name = "Join Us üëãüèø"
        weight = 2
        url = "https://codeyourfuture.io/volunteer/"
    [[menus.secondary]]
        name = "Support ü´∂üèº"
        weight = 3
        url = "https://codeyourfuture.io/donate"    

[params]
googleFonts="https://fonts.googleapis.com/css2?family=Raleway:wght@300;600;800;900&display=swap"
description = "A free and open source technical curriculum platform."
main_website = "https://curriculum.codeyourfuture.io/"
main_org_name = "Code Your Future"
our_name="The Docs"
org = "https://github.com/CodeYourFuture"
repo = "https://github.com/CodeYourFuture/curriculum/"
owner = "CodeYourFuture"
root = "curriculum"
orgapi = "https://api.github.com/repos/CodeYourFuture"
[caches.getresource]
maxAge="6h"

[security.funcs]
# Allow accessing a GitHub bearer token to avoid rate limits when doing HTTP fetches to the GitHub API.
# This can be generated at https://github.com/settings/tokens?type=beta and needs read-only access to all public CYF GitHub repos.
getenv = ["^HUGO_CURRICULUM_GITHUB_BEARER_TOKEN$"]


[markup]
# I've configured markdown so you don't have to
  [markup.tableOfContents]
    endLevel = 2
    ordered = true
    startLevel = 2
    [markup.goldmark.renderer]
# Enable HTML codeblocks, e.g. for <details> blocks
      unsafe = true

theme = "common-theme"

#this makes the section nav go the right way
# because of this 'unexpected behaviour' https://gohugo.io/methods/page/nextinsection/
[page]
  nextPrevInSectionSortOrder = 'asc'
  nextPrevSortOrder = 'asc'
