title = "Tracks"
description="Short focused courses working towards specific roles"
baseURL = "https://tracks.codeyourfuture.io/"

[module]
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/org-cyf-theme"
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/org-cyf-guides" 
    [[module.imports.mounts]]
      source = "content"
      target = "content/guides"
  [[module.imports]]
    path = "github.com/CodeYourFuture/CYF-PD" 
    [[module.imports.mounts]]
      source = "content/blocks"
      target = "content/pd/blocks"
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/org-cyf-how-this-works"
    [[module.imports.mounts]]
      source = "content"
      target = "content/how-this-works"
