baseURL = "/"
title = "Our Platform"
sectionPagesMenu = "main"
enableEmoji = true
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    contentDir = 'content/en'
    languageCode = 'en-GB'
    languageName = 'English'

[menus]
    [[menus.secondary]]
        name = "Menu 1 üëàüèæ"
        weight = 1
        url = ""
     [[menus.secondary]]
        name = "Menu 2 üëãüèø"
        weight = 2
        url = ""
    [[menus.secondary]]
        name = "Menu 3 ü´∂üèº"
        weight = 3
        url = ""

[params]
googleFonts="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&family=Raleway:wght@300;600;800;900&display=swap"
description = "A free and open source software development programme."
startTime="10:00"
# main_website = ""
# main_org_name = "eg Code Your Future"
# our_name = "alias for in text replacement"
# org = "https://github.com/YOUR_ORG_HERE"
# repo = "https://github.com/YOUR_ORG_HERE/YOUR_REPO/"
# owner = "YOUR_ORG_HERE"
# root = "YOUR_REPO_I_THINK"
# orgapi = "https://api.github.com/repos/YOUR_ORG_HERE/"
# pdrepo = "PD-curriculum-repo"

#markdown configs cannot be inherited so are not set, look in org-cyf-theme for examples
# this seems also to not be heritable but you do need it
[page]
  nextPrevInSectionSortOrder = 'asc'
  nextPrevSortOrder = 'asc'

[caches.getjson]
# Disable caching of fetches - we want every build to get up to date content for issues, so that if people make clarifications or fixes to issues, we pick them up.
maxAge = 0

[security.funcs]
# Allow accessing a GitHub bearer token to avoid rate limits when doing HTTP fetches to the GitHub API.
# This can be generated at https://github.com/settings/tokens?type=beta and needs read-only access to all public CYF GitHub repos.
getenv = ["^HUGO_CURRICULUM_GITHUB_BEARER_TOKEN$"]


[module]
  [module.hugoVersion]
    extended = true
    min = "0.133.0"
