title = "CYF Courses"
baseURL = "https://curriculum.codeyourfuture.io/"

[module]
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/common-theme" 
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/common-content" 
    [[module.imports.mounts]]
      source = "en"
      target = "content"
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/org-cyf-guides" 
    [[module.imports.mounts]]
      source = "content"
      target = "content/guides"  
      
[menus]
  [[menus.secondary]]
    name = "Guides ğŸ‘ˆğŸ¾"
    weight = 1
    url = "/guides"
  [[menus.secondary]]
    name = "Join Us ğŸ‘‹ğŸ¿"
    weight = 2
    url = "https://codeyourfuture.io/volunteers/"
  [[menus.secondary]]
    name = "Support ğŸ«¶ğŸ¼"
    weight = 3
    url = "https://codeyourfuture.io/donate/"

[[menus.syllabus]]
  name="Intro to Digital"
  url="https://codeyourfuture.io/itc/"
  weight = 1

[[menus.syllabus]]
  name="Intro to Programming"
  url="https://programming.codeyourfuture.io/"
  weight = 2

[[menus.syllabus]]
  name="The Piscine"
  url="https://piscine.codeyourfuture.io/"
  weight = 3

[[menus.syllabus]]
  name="Software Development"
  url="https://sdc.codeyourfuture.io/"
  weight = 4

[[menus.syllabus]]
  name="The Launch"
  url="https://launch.codeyourfuture.io/"
  weight = 5

[[menus.syllabus]]
  name="Tracks"
  url="https://tracks.codeyourfuture.io/"
  weight = 6

[[menus.syllabus]]
  name="Systems Engineering"
  url="https://systems.codeyourfuture.io/"
  weight = 7


[params]
googleFonts="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;500;700&family=Inter:wght@400;800&display=swap"
description = "A free and open source software development programme."
main_website = "https://codeyourfuture.io/"
main_org_name = "Code Your Future"
our_name="CYF"
org = "https://github.com/CodeYourFuture"
repo = "https://github.com/CodeYourFuture/curriculum/"
root = "curriculum"


theme = "common-theme"